//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenScan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreenScan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string AboutCopyright {
            get {
                return ResourceManager.GetString("AboutCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created by Péter Major.
        /// </summary>
        public static string AboutCreatedBy {
            get {
                return ResourceManager.GetString("AboutCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string CommonBrowse {
            get {
                return ResourceManager.GetString("CommonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string CommonFinish {
            get {
                return ResourceManager.GetString("CommonFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string CommonInformation {
            get {
                return ResourceManager.GetString("CommonInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string CommonNext {
            get {
                return ResourceManager.GetString("CommonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string CommonPrevious {
            get {
                return ResourceManager.GetString("CommonPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string CommonProgress {
            get {
                return ResourceManager.GetString("CommonProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string CommonResults {
            get {
                return ResourceManager.GetString("CommonResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string CommonStart {
            get {
                return ResourceManager.GetString("CommonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zebra|Rainbow|Shaded rainbow|Scale|Shaded scale|Blinn|Textured.
        /// </summary>
        public static string EnumGraphicsCanvasShadingModes {
            get {
                return ResourceManager.GetString("EnumGraphicsCanvasShadingModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth|Color|Depth with color|Infrared.
        /// </summary>
        public static string EnumKinectManagerModes {
            get {
                return ResourceManager.GetString("EnumKinectManagerModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-axis|Two-axis|Volumetric.
        /// </summary>
        public static string EnumRotatingScannerModes {
            get {
                return ResourceManager.GetString("EnumRotatingScannerModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay|Depth - left leg|Depth - right leg|Texture - left leg|Texture - right leg|Model.
        /// </summary>
        public static string EnumRotatingScannerViews {
            get {
                return ResourceManager.GetString("EnumRotatingScannerViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay|Projection|Slice|Model.
        /// </summary>
        public static string EnumRotatingScannerVolumetricViews {
            get {
                return ResourceManager.GetString("EnumRotatingScannerVolumetricViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string KinectCalibrationClear {
            get {
                return ResourceManager.GetString("KinectCalibrationClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string KinectCalibrationColor {
            get {
                return ResourceManager.GetString("KinectCalibrationColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string KinectCalibrationControls {
            get {
                return ResourceManager.GetString("KinectCalibrationControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string KinectCalibrationDepth {
            get {
                return ResourceManager.GetString("KinectCalibrationDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrared.
        /// </summary>
        public static string KinectCalibrationInfrared {
            get {
                return ResourceManager.GetString("KinectCalibrationInfrared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string KinectCalibrationPath {
            get {
                return ResourceManager.GetString("KinectCalibrationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select calibration directory.
        /// </summary>
        public static string KinectCalibrationSelectDirectory {
            get {
                return ResourceManager.GetString("KinectCalibrationSelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} positions captured..
        /// </summary>
        public static string KinectCalibrationStatus {
            get {
                return ResourceManager.GetString("KinectCalibrationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect Calibration.
        /// </summary>
        public static string KinectCalibrationTitle {
            get {
                return ResourceManager.GetString("KinectCalibrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string MenuDevice {
            get {
                return ResourceManager.GetString("MenuDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate....
        /// </summary>
        public static string MenuDeviceCalibrate {
            get {
                return ResourceManager.GetString("MenuDeviceCalibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string MenuDeviceDevice {
            get {
                return ResourceManager.GetString("MenuDeviceDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string MenuDeviceMode {
            get {
                return ResourceManager.GetString("MenuDeviceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string MenuDeviceStart {
            get {
                return ResourceManager.GetString("MenuDeviceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string MenuDeviceStop {
            get {
                return ResourceManager.GetString("MenuDeviceStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as.
        /// </summary>
        public static string MenuExportAs {
            get {
                return ResourceManager.GetString("MenuExportAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collada DAE.
        /// </summary>
        public static string MenuExportAsDae {
            get {
                return ResourceManager.GetString("MenuExportAsDae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoCAD DXF.
        /// </summary>
        public static string MenuExportAsDxf {
            get {
                return ResourceManager.GetString("MenuExportAsDxf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodesk FBX.
        /// </summary>
        public static string MenuExportAsFbx {
            get {
                return ResourceManager.GetString("MenuExportAsFbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector4 FL4.
        /// </summary>
        public static string MenuExportAsFl4 {
            get {
                return ResourceManager.GetString("MenuExportAsFl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias OBJ.
        /// </summary>
        public static string MenuExportAsObj {
            get {
                return ResourceManager.GetString("MenuExportAsObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image PNG.
        /// </summary>
        public static string MenuExportAsPng {
            get {
                return ResourceManager.GetString("MenuExportAsPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As original.
        /// </summary>
        public static string MenuExportAsPngAsOriginal {
            get {
                return ResourceManager.GetString("MenuExportAsPngAsOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As screenshot.
        /// </summary>
        public static string MenuExportAsPngAsScreenshot {
            get {
                return ResourceManager.GetString("MenuExportAsPngAsScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary STL.
        /// </summary>
        public static string MenuExportAsStl {
            get {
                return ResourceManager.GetString("MenuExportAsStl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse save directory.
        /// </summary>
        public static string MenuFileBrowseSaveDirectory {
            get {
                return ResourceManager.GetString("MenuFileBrowseSaveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open model....
        /// </summary>
        public static string MenuOpenModel {
            get {
                return ResourceManager.GetString("MenuOpenModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save model.
        /// </summary>
        public static string MenuSaveModel {
            get {
                return ResourceManager.GetString("MenuSaveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turntable.
        /// </summary>
        public static string MenuTurntable {
            get {
                return ResourceManager.GetString("MenuTurntable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate....
        /// </summary>
        public static string MenuTurntableCalibrate {
            get {
                return ResourceManager.GetString("MenuTurntableCalibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count steps....
        /// </summary>
        public static string MenuTurntableCountSteps {
            get {
                return ResourceManager.GetString("MenuTurntableCountSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to origin.
        /// </summary>
        public static string MenuTurntableReturnToOrigin {
            get {
                return ResourceManager.GetString("MenuTurntableReturnToOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string MenuTurntableScan {
            get {
                return ResourceManager.GetString("MenuTurntableScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string MenuTurntableStop {
            get {
                return ResourceManager.GetString("MenuTurntableStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string OpenFileTitle {
            get {
                return ResourceManager.GetString("OpenFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreenScan raw files.
        /// </summary>
        public static string OpenRawFileFilter {
            get {
                return ResourceManager.GetString("OpenRawFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreenScan Turntable raw files.
        /// </summary>
        public static string OpenTurntableRawFileFilter {
            get {
                return ResourceManager.GetString("OpenTurntableRawFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening was unsuccessful..
        /// </summary>
        public static string OpenUnsuccesful {
            get {
                return ResourceManager.GetString("OpenUnsuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romoted from {0}..
        /// </summary>
        public static string RemotingRemotedFrom {
            get {
                return ResourceManager.GetString("RemotingRemotedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} remote(s) connected..
        /// </summary>
        public static string RemotingRemotesConnected {
            get {
                return ResourceManager.GetString("RemotingRemotesConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving was unsuccessful!.
        /// </summary>
        public static string SaveUnsuccesful {
            get {
                return ResourceManager.GetString("SaveUnsuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color X disposition (pixels).
        /// </summary>
        public static string SettingColorDispositionX {
            get {
                return ResourceManager.GetString("SettingColorDispositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Y disposition (pixels).
        /// </summary>
        public static string SettingColorDispositionY {
            get {
                return ResourceManager.GetString("SettingColorDispositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color extrinsics.
        /// </summary>
        public static string SettingColorExtrinsics {
            get {
                return ResourceManager.GetString("SettingColorExtrinsics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color intrinsic matrix.
        /// </summary>
        public static string SettingColorIntrinsics {
            get {
                return ResourceManager.GetString("SettingColorIntrinsics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color remapping.
        /// </summary>
        public static string SettingColorRemapping {
            get {
                return ResourceManager.GetString("SettingColorRemapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color X scale (units).
        /// </summary>
        public static string SettingColorScaleX {
            get {
                return ResourceManager.GetString("SettingColorScaleX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Y scale (units).
        /// </summary>
        public static string SettingColorScaleY {
            get {
                return ResourceManager.GetString("SettingColorScaleY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth averaging buffer size (slots).
        /// </summary>
        public static string SettingDepthAveraging {
            get {
                return ResourceManager.GetString("SettingDepthAveraging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth coefficients (units).
        /// </summary>
        public static string SettingDepthCoeffs {
            get {
                return ResourceManager.GetString("SettingDepthCoeffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth Gauss filtering (iterations).
        /// </summary>
        public static string SettingDepthGaussIterations {
            get {
                return ResourceManager.GetString("SettingDepthGaussIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth Gauss filtering sigma (units).
        /// </summary>
        public static string SettingDepthGaussSigma {
            get {
                return ResourceManager.GetString("SettingDepthGaussSigma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth maximum (meters).
        /// </summary>
        public static string SettingDepthMaximum {
            get {
                return ResourceManager.GetString("SettingDepthMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth minimum (meters).
        /// </summary>
        public static string SettingDepthMinimum {
            get {
                return ResourceManager.GetString("SettingDepthMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth to IR mapping.
        /// </summary>
        public static string SettingDepthToIRMapping {
            get {
                return ResourceManager.GetString("SettingDepthToIRMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string SettingGroupCamera {
            get {
                return ResourceManager.GetString("SettingGroupCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect.
        /// </summary>
        public static string SettingGroupKinect {
            get {
                return ResourceManager.GetString("SettingGroupKinect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Applies to Kinect for Windows only.
        /// </summary>
        public static string SettingGroupKinectFooter {
            get {
                return ResourceManager.GetString("SettingGroupKinectFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string SettingGroupPerformance {
            get {
                return ResourceManager.GetString("SettingGroupPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocessing.
        /// </summary>
        public static string SettingGroupPreprocessing {
            get {
                return ResourceManager.GetString("SettingGroupPreprocessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string SettingGroupSave {
            get {
                return ResourceManager.GetString("SettingGroupSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading.
        /// </summary>
        public static string SettingGroupShading {
            get {
                return ResourceManager.GetString("SettingGroupShading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turntable.
        /// </summary>
        public static string SettingGroupTurntable {
            get {
                return ResourceManager.GetString("SettingGroupTurntable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string SettingGroupView {
            get {
                return ResourceManager.GetString("SettingGroupView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrared distortion coefficients {K1, K2; P1, P2}.
        /// </summary>
        public static string SettingInfraredDistortion {
            get {
                return ResourceManager.GetString("SettingInfraredDistortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrared distortion correction enabled.
        /// </summary>
        public static string SettingInfraredDistortionCorrectionEnabled {
            get {
                return ResourceManager.GetString("SettingInfraredDistortionCorrectionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrared intrinsic matrix.
        /// </summary>
        public static string SettingInfraredIntrinsics {
            get {
                return ResourceManager.GetString("SettingInfraredIntrinsics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitter enabled*.
        /// </summary>
        public static string SettingKinectEmitterEnabled {
            get {
                return ResourceManager.GetString("SettingKinectEmitterEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string SettingKinectMode {
            get {
                return ResourceManager.GetString("SettingKinectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near mode*.
        /// </summary>
        public static string SettingKinectNearMode {
            get {
                return ResourceManager.GetString("SettingKinectNearMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move X (units).
        /// </summary>
        public static string SettingMoveX {
            get {
                return ResourceManager.GetString("SettingMoveX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Y (units).
        /// </summary>
        public static string SettingMoveY {
            get {
                return ResourceManager.GetString("SettingMoveY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation (units).
        /// </summary>
        public static string SettingRotation {
            get {
                return ResourceManager.GetString("SettingRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation X (degrees).
        /// </summary>
        public static string SettingRotationX {
            get {
                return ResourceManager.GetString("SettingRotationX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Y (degrees).
        /// </summary>
        public static string SettingRotationY {
            get {
                return ResourceManager.GetString("SettingRotationY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Z (degrees).
        /// </summary>
        public static string SettingRotationZ {
            get {
                return ResourceManager.GetString("SettingRotationZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration directory.
        /// </summary>
        public static string SettingSaveCalibrationDirectory {
            get {
                return ResourceManager.GetString("SettingSaveCalibrationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string SettingSaveDirectory {
            get {
                return ResourceManager.GetString("SettingSaveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string SettingSaveLabel {
            get {
                return ResourceManager.GetString("SettingSaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model resolution (vertices).
        /// </summary>
        public static string SettingSaveModelResolution {
            get {
                return ResourceManager.GetString("SettingSaveModelResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No timestamp if label specified.
        /// </summary>
        public static string SettingSaveNoTimestamp {
            get {
                return ResourceManager.GetString("SettingSaveNoTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling power (10^x).
        /// </summary>
        public static string SettingSaveScalingPower {
            get {
                return ResourceManager.GetString("SettingSaveScalingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture resolution (pixels).
        /// </summary>
        public static string SettingSaveTextureResolution {
            get {
                return ResourceManager.GetString("SettingSaveTextureResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale (units).
        /// </summary>
        public static string SettingScale {
            get {
                return ResourceManager.GetString("SettingScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string SettingShadingMode {
            get {
                return ResourceManager.GetString("SettingShadingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading periode (meters).
        /// </summary>
        public static string SettingShadingPeriode {
            get {
                return ResourceManager.GetString("SettingShadingPeriode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading phase (units).
        /// </summary>
        public static string SettingShadingPhase {
            get {
                return ResourceManager.GetString("SettingShadingPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation X (meters).
        /// </summary>
        public static string SettingTranslationX {
            get {
                return ResourceManager.GetString("SettingTranslationX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Y (meters).
        /// </summary>
        public static string SettingTranslationY {
            get {
                return ResourceManager.GetString("SettingTranslationY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Z (meters).
        /// </summary>
        public static string SettingTranslationZ {
            get {
                return ResourceManager.GetString("SettingTranslationZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle grid resolution.
        /// </summary>
        public static string SettingTriangleGridResolution {
            get {
                return ResourceManager.GetString("SettingTriangleGridResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle remove limit (units).
        /// </summary>
        public static string SettingTriangleRemoveLimit {
            get {
                return ResourceManager.GetString("SettingTriangleRemoveLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string SettingTurntableAxialView {
            get {
                return ResourceManager.GetString("SettingTurntableAxialView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipping height (meters).
        /// </summary>
        public static string SettingTurntableClippingHeight {
            get {
                return ResourceManager.GetString("SettingTurntableClippingHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipping radius (meters).
        /// </summary>
        public static string SettingTurntableClippingRadius {
            get {
                return ResourceManager.GetString("SettingTurntableClippingRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg distance (meters).
        /// </summary>
        public static string SettingTurntableCoreX {
            get {
                return ResourceManager.GetString("SettingTurntableCoreX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg position (meters).
        /// </summary>
        public static string SettingTurntableCoreY {
            get {
                return ResourceManager.GetString("SettingTurntableCoreY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube resolution (voxels).
        /// </summary>
        public static string SettingTurntableCubeResolution {
            get {
                return ResourceManager.GetString("SettingTurntableCubeResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube size (centimeters).
        /// </summary>
        public static string SettingTurntableCubeSize {
            get {
                return ResourceManager.GetString("SettingTurntableCubeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string SettingTurntableMode {
            get {
                return ResourceManager.GetString("SettingTurntableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model resolution (vertices/leg).
        /// </summary>
        public static string SettingTurntableModelResolution {
            get {
                return ResourceManager.GetString("SettingTurntableModelResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current depth (units).
        /// </summary>
        public static string SettingTurntableSlice {
            get {
                return ResourceManager.GetString("SettingTurntableSlice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture resolution (pixels/leg).
        /// </summary>
        public static string SettingTurntableTextureResolution {
            get {
                return ResourceManager.GetString("SettingTurntableTextureResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold (units).
        /// </summary>
        public static string SettingTurntableThreshold {
            get {
                return ResourceManager.GetString("SettingTurntableThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turntable matrix.
        /// </summary>
        public static string SettingTurntableTransform {
            get {
                return ResourceManager.GetString("SettingTurntableTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string SettingTurntableVolumetricView {
            get {
                return ResourceManager.GetString("SettingTurntableVolumetricView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use module shading (if available).
        /// </summary>
        public static string SettingUseModuleShading {
            get {
                return ResourceManager.GetString("SettingUseModuleShading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireframe shading.
        /// </summary>
        public static string SettingWireframeShading {
            get {
                return ResourceManager.GetString("SettingWireframeShading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to Kinect!.
        /// </summary>
        public static string StatusCannotConnectToKinect {
            get {
                return ResourceManager.GetString("StatusCannotConnectToKinect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device can not be opened. May be on low power, brandwith or may be already in use..
        /// </summary>
        public static string StatusDeviceCannotBeOpened {
            get {
                return ResourceManager.GetString("StatusDeviceCannotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File loaded successfully..
        /// </summary>
        public static string StatusFileLoadedSuccesfully {
            get {
                return ResourceManager.GetString("StatusFileLoadedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string StatusLoading {
            get {
                return ResourceManager.GetString("StatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Kinect....
        /// </summary>
        public static string StatusPreparingKinect {
            get {
                return ResourceManager.GetString("StatusPreparingKinect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save complete..
        /// </summary>
        public static string StatusSaveComplete {
            get {
                return ResourceManager.GetString("StatusSaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save in progress....
        /// </summary>
        public static string StatusSaveInProgress {
            get {
                return ResourceManager.GetString("StatusSaveInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string StatusStarting {
            get {
                return ResourceManager.GetString("StatusStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        public static string StatusStopping {
            get {
                return ResourceManager.GetString("StatusStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove any objects from the turntable, then click next..
        /// </summary>
        public static string TurntableCalibrationStep1 {
            get {
                return ResourceManager.GetString("TurntableCalibrationStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the turntable on the image with the mouse: move the cursor to the upper-left corner of the imaginary boundary rectangle of the turntable, then hold down the left button, and move the mouse to the bottom-right corner and release the button. You may repeat this procedure to select the turntable correctly. Click next to continue..
        /// </summary>
        public static string TurntableCalibrationStep2 {
            get {
                return ResourceManager.GetString("TurntableCalibrationStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the calibration etalon to the turntable: the etalon should face toward the scanner&apos;s mirror and it should snap in the holes on the turntable. Click next to continue..
        /// </summary>
        public static string TurntableCalibrationStep3 {
            get {
                return ResourceManager.GetString("TurntableCalibrationStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the etalon on the image with the mouse (like in step 2). Click next to preview the calibration results..
        /// </summary>
        public static string TurntableCalibrationStep4 {
            get {
                return ResourceManager.GetString("TurntableCalibrationStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if the the turntable&apos;s position has been selected correctly. Click to finish to save the results..
        /// </summary>
        public static string TurntableCalibrationStep5 {
            get {
                return ResourceManager.GetString("TurntableCalibrationStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turntable Calibration.
        /// </summary>
        public static string TurntableCalibrationTitle {
            get {
                return ResourceManager.GetString("TurntableCalibrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of measurement.
        /// </summary>
        public static string TurntableStepCounterCloseTitle {
            get {
                return ResourceManager.GetString("TurntableStepCounterCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this tool, you can count the steps corresponding to one full rotation of the turntable. Press Start to begin!.
        /// </summary>
        public static string TurntableStepCounterInformation {
            get {
                return ResourceManager.GetString("TurntableStepCounterInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pass(es)..
        /// </summary>
        public static string TurntableStepCounterPasses {
            get {
                return ResourceManager.GetString("TurntableStepCounterPasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the results as settings?.
        /// </summary>
        public static string TurntableStepCounterSaveResults {
            get {
                return ResourceManager.GetString("TurntableStepCounterSaveResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to origin.....
        /// </summary>
        public static string TurntableStepCounterStatusMovingToOrigin {
            get {
                return ResourceManager.GetString("TurntableStepCounterStatusMovingToOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premovement....
        /// </summary>
        public static string TurntableStepCounterStatusPremovement {
            get {
                return ResourceManager.GetString("TurntableStepCounterStatusPremovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string TurntableStepCounterStatusReady {
            get {
                return ResourceManager.GetString("TurntableStepCounterStatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for magnetic switch....
        /// </summary>
        public static string TurntableStepCounterStatusWaitingForSwitch {
            get {
                return ResourceManager.GetString("TurntableStepCounterStatusWaitingForSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steps..
        /// </summary>
        public static string TurntableStepCounterSteps {
            get {
                return ResourceManager.GetString("TurntableStepCounterSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steps per rotation..
        /// </summary>
        public static string TurntableStepCounterStepsPerRotation {
            get {
                return ResourceManager.GetString("TurntableStepCounterStepsPerRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turntable step counter.
        /// </summary>
        public static string TurntableStepCounterTitle {
            get {
                return ResourceManager.GetString("TurntableStepCounterTitle", resourceCulture);
            }
        }
    }
}
