#pragma once
#pragma unmanaged
#define WIN32_LEAN_AND_MEAN  
#include <Windows.h>
#include <winerror.h>
#include <stdlib.h>
#include <memory.h>
#include <malloc.h>
#include <tchar.h>
#include <comdef.h>
#include <stdio.h>
#include <d3d11.h>
#include <string.h>
#include <math.h>
#include <DirectXMath.h>